sudo: required
services:
  - docker

before_install:
  - docker build -t zelucena/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zelucena/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-sa-east-1-947887025102"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY